"use strict";
var frutas = ['maça', 'uva', 'banana'];
frutas.push('pera');
console.log(frutas);
var diaSemana = [];
diaSemana.push('segunda');
diaSemana.push(3);
console.log(diaSemana);
var opcoes = ['não ok', 'ola', false];
opcoes.push('ok');
opcoes.push(1);
opcoes.push(true);
console.log(opcoes);
